export * from './identity.model';
export * from './acaodeacompanhamento.model';
export * from './user.model';
export * from './grupo.model';
export * from './frames.model';
export * from './grupo-agencia.model'
export * from './areadenegocio.model'
export * from './canaldistribuicao.model'
export * from './motivorecusa.model'
export * from './menu.model';
export * from './motivocancelamento.model'
export * from './retornoligacao.model'
export * from './vinculobnb.model'
export * from './empresas.model'
export * from './tiposdeseguro.model'
export * from './tipodeproduto.model'

export * from './situacao.model'
export * from './inbox.model'
export * from './anexo-inbox.model'
export * from './solicitacao.model'
